name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagic-dev poppler-utils curl
          curl -L https://cpanmin.us | perl - -v -n --installdeps .
      - name: Run tests
        run: |
          perl Makefile.PL
          make test
